### ISSUE TITLE
Difficulties with import process

### ISSUE THREAD

**Issue by voska** [zhdenny/bar_assistant_database#1]
1. the zip file should be chown'd to 1000:1000, not 33:33.
2. since it's hosted on dropbox, they add a _meta file to the zip which messes up the import, so unzip, delete `_meta`, then rezip.
3. the php artisan command pulls from /storage/bar-assistant, so you can literally just call the name of the file when you exec into the container. No need for a full path, that screws things up.

**Comment by zhdenny** [comment]
1. The zip file should be chown'd to match whatever your permissions are for Bar-Assistant. Looks like this was fixed in the past months by the dev. 1000:1000 is good. I'll update the instructions.
2. I checked this out. Look at the content of the `_meta.json` file. It is NOT something dropbox generates. It is from Bar-Assistant. When I make a backup zip, the `_meta.json` is included in the zip file by Bar-Assistant. That file contains important version information checks.

In addition....in dropbox, be sure you are downloading the file and not the folder. Dropbox has two download buttons. The big one at the top will tell dropbox to zip up the entire folder and download it for. Don't do that (I know you didn't, I'm just giving more info). screenshot to help.
![image](https://github.com/user-attachments/assets/c01b06f9-e088-408d-84a5-f4ec893d8453)

3. My import instructions do not mention the full path. The instructions only mention the "name_of_file.zip"
```
#This will innitiate the database import
#Replace "name_of_file.zip" with the database zip filename
php artisan bar:import-recipes name_of_file.zip
```

With all that said though....currently there appears to be an issue with bar zip file imports. I've reported it to the developer.
https://github.com/karlomikus/bar-assistant/issues/326

**Comment by zhdenny** [comment]
Bar Assistant Developer fixed the Export/Import issues and I've addressed all issues.
Closing this now.
